# Generated by Django 5.2.6 on 2025-10-06 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formoryapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='valid_from',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='valid_to',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
