# Generated by Django 5.2.6 on 2025-09-10 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formoryapp', '0002_alter_category_meta_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='Product',
            new_name='product',
        ),
    ]
