# Generated by Django 5.2.6 on 2025-10-07 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formoryapp', '0002_alter_offer_valid_from_alter_offer_valid_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='discount_percentage',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='original_price',
            field=models.FloatField(blank=True),
        ),
    ]
