# Generated by Django 5.2.6 on 2025-10-07 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formoryapp', '0004_alter_product_original_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='original_price',
            field=models.FloatField(),
        ),
    ]
