# Generated by Django 5.2.6 on 2025-10-07 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formoryapp', '0005_alter_product_original_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Offer',
        ),
    ]
