# Generated by Django 5.2.6 on 2025-09-12 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formoryapp', '0005_product_unit_type_alter_product_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='product_unit',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
