# Generated by Django 5.2.6 on 2025-09-12 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formoryapp', '0007_remove_cart_product_unit_alter_product_unit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='product',
            name='unit_type',
        ),
    ]
