# Generated by Django 5.2.6 on 2025-10-08 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formoryapp', '0007_offer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Offer',
        ),
    ]
