# Generated by Django 5.2.6 on 2025-09-22 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formoryapp', '0014_alter_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
