# Generated by Django 5.2.6 on 2025-09-13 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('Fruit', 'Fruit'), ('Vegetable', 'Vegetable'), ('Grain', 'Grain'), ('Legume', 'Legume'), ('Nut', 'Nut'), ('Dairy', 'Dairy'), ('Meat', 'Meat'), ('Egg', 'Egg'), ('Oil', 'Oils & Fats')], max_length=50)),
                ('age_group', models.CharField(choices=[('Kids', 'Kids'), ('Teens', 'Teens'), ('Adults', 'Adults')], default='Adults', max_length=20)),
                ('image', models.ImageField(upload_to='food_images/')),
            ],
        ),
    ]
