# Generated by Django 5.2.6 on 2025-09-13 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutricapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Food',
        ),
    ]
