# Generated by Django 5.2.6 on 2025-09-16 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formoryapp', '0011_product_is_recipe_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_recipe',
        ),
    ]
