# Generated by Django 5.2.6 on 2025-09-24 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formoryapp', '0015_order_razorpay_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='original_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
