# Generated by Django 5.2.7 on 2025-10-07 07:08

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formoryapp', '0017_deliverypartner_alter_order_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_type', models.CharField(choices=[('deal_of_the_week', 'Deal of the Week'), ('combo_offer', 'Combo Offer')], max_length=50)),
                ('discount_percentage', models.PositiveIntegerField(default=0)),
                ('start_time', models.DateTimeField(default=datetime.datetime.now)),
                ('end_time', models.DateTimeField()),
                ('active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='formoryapp.product')),
            ],
        ),
    ]
