# Generated by Django 5.2.7 on 2025-10-07 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formoryapp', '0019_alter_product_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formoryapp.product'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
