# Generated by Django 5.2.7 on 2025-10-08 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formoryapp', '0020_alter_offer_product_alter_offer_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='discount_percentage',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='offer',
            name='offer_type',
            field=models.CharField(choices=[('deal of the week', 'Deal of the Week'), ('combo_offer', 'Combo Offer')], max_length=50),
        ),
    ]
