# Generated by Django 5.2.7 on 2025-10-08 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formoryapp', '0021_alter_offer_discount_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='offer_type',
            field=models.CharField(choices=[('deal_of_the_week', 'Deal of the Week'), ('combo_offer', 'Combo Offer')], max_length=50),
        ),
    ]
