# Generated by Django 5.2.7 on 2025-10-08 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formoryapp', '0022_alter_offer_offer_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=5),
        ),
    ]
