# Generated by Django 5.2.6 on 2025-09-12 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formoryapp', '0004_product_unit_alter_product_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit_type',
            field=models.CharField(choices=[('weight', 'Weight'), ('volume', 'Volume'), ('piece', 'Piece')], default='piece', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('weight', 'Weight'), ('volume', 'Volume'), ('piece', 'Piece')], default='g', max_length=10),
        ),
    ]
