# Generated by Django 5.2.6 on 2025-09-12 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formoryapp', '0006_cart_product_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='product_unit',
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('g', 'Grams'), ('kg', 'Kilograms'), ('ml', 'Millilitres'), ('l', 'Litres'), ('pcs', 'Pieces')], default='g', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_type',
            field=models.CharField(choices=[('kg', 'Kilograms / Grams'), ('ml', 'Milliliters / Liters'), ('pcs', 'Pieces')], default='pcs', max_length=10),
        ),
    ]
